# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/model.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'proto/model.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11proto/model.proto\"\x14\n\x12ModelGetWeightsReq\"\x14\n\x12InitializeModelReq\"$\n\x12InitializeModelRes\x12\x0e\n\x06status\x18\x01 \x01(\r\":\n\rClientWeights\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\x12\x18\n\x10\x63lient_data_size\x18\x02 \x01(\r\"\x1a\n\x07Weights\x12\x0f\n\x07weights\x18\x01 \x01(\x0c\"*\n\x18\x41ggregateModelWeightsRes\x12\x0e\n\x06status\x18\x01 \x01(\r2\xc9\x01\n\x0cModelService\x12;\n\x0fInitializeModel\x12\x13.InitializeModelReq\x1a\x13.InitializeModelRes\x12\x36\n\x0fModelGetWeights\x12\x13.ModelGetWeightsReq\x1a\x0e.ClientWeights\x12\x44\n\x15\x41ggregateModelWeights\x12\x0e.ClientWeights\x1a\x19.AggregateModelWeightsRes(\x01\x42\rZ\x0bpkg/modelpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.model_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013pkg/modelpb'
  _globals['_MODELGETWEIGHTSREQ']._serialized_start=21
  _globals['_MODELGETWEIGHTSREQ']._serialized_end=41
  _globals['_INITIALIZEMODELREQ']._serialized_start=43
  _globals['_INITIALIZEMODELREQ']._serialized_end=63
  _globals['_INITIALIZEMODELRES']._serialized_start=65
  _globals['_INITIALIZEMODELRES']._serialized_end=101
  _globals['_CLIENTWEIGHTS']._serialized_start=103
  _globals['_CLIENTWEIGHTS']._serialized_end=161
  _globals['_WEIGHTS']._serialized_start=163
  _globals['_WEIGHTS']._serialized_end=189
  _globals['_AGGREGATEMODELWEIGHTSRES']._serialized_start=191
  _globals['_AGGREGATEMODELWEIGHTSRES']._serialized_end=233
  _globals['_MODELSERVICE']._serialized_start=236
  _globals['_MODELSERVICE']._serialized_end=437
# @@protoc_insertion_point(module_scope)
