# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import model_pb2 as proto_dot_model__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/model_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeModel = channel.unary_unary(
                '/ModelService/InitializeModel',
                request_serializer=proto_dot_model__pb2.InitializeModelReq.SerializeToString,
                response_deserializer=proto_dot_model__pb2.InitializeModelRes.FromString,
                _registered_method=True)
        self.ModelGetWeights = channel.unary_unary(
                '/ModelService/ModelGetWeights',
                request_serializer=proto_dot_model__pb2.ModelGetWeightsReq.SerializeToString,
                response_deserializer=proto_dot_model__pb2.ClientWeights.FromString,
                _registered_method=True)
        self.AggregateModelWeights = channel.stream_unary(
                '/ModelService/AggregateModelWeights',
                request_serializer=proto_dot_model__pb2.ClientWeights.SerializeToString,
                response_deserializer=proto_dot_model__pb2.AggregateModelWeightsRes.FromString,
                _registered_method=True)


class ModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ModelGetWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AggregateModelWeights(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeModel': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeModel,
                    request_deserializer=proto_dot_model__pb2.InitializeModelReq.FromString,
                    response_serializer=proto_dot_model__pb2.InitializeModelRes.SerializeToString,
            ),
            'ModelGetWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.ModelGetWeights,
                    request_deserializer=proto_dot_model__pb2.ModelGetWeightsReq.FromString,
                    response_serializer=proto_dot_model__pb2.ClientWeights.SerializeToString,
            ),
            'AggregateModelWeights': grpc.stream_unary_rpc_method_handler(
                    servicer.AggregateModelWeights,
                    request_deserializer=proto_dot_model__pb2.ClientWeights.FromString,
                    response_serializer=proto_dot_model__pb2.AggregateModelWeightsRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ModelService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ModelService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ModelService/InitializeModel',
            proto_dot_model__pb2.InitializeModelReq.SerializeToString,
            proto_dot_model__pb2.InitializeModelRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ModelGetWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ModelService/ModelGetWeights',
            proto_dot_model__pb2.ModelGetWeightsReq.SerializeToString,
            proto_dot_model__pb2.ClientWeights.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AggregateModelWeights(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ModelService/AggregateModelWeights',
            proto_dot_model__pb2.ClientWeights.SerializeToString,
            proto_dot_model__pb2.AggregateModelWeightsRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
