# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/fedlearn.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'proto/fedlearn.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/fedlearn.proto\"S\n\x0eSendWeightsReq\x12\x11\n\tclient_id\x18\x01 \x01(\r\x12\x18\n\x10\x63lient_data_size\x18\x02 \x01(\r\x12\x14\n\x0cweights_data\x18\x03 \x01(\x0c\" \n\x0eSendWeightsRes\x12\x0e\n\x06status\x18\x01 \x01(\t\"@\n\x11RequestWeightsReq\x12\x11\n\tclient_id\x18\x01 \x01(\r\x12\x18\n\x10\x63lient_data_size\x18\x02 \x01(\r\"<\n\x11RequestWeightsRes\x12\x14\n\x0cweights_data\x18\x01 \x01(\x0c\x12\x11\n\tclient_id\x18\x02 \x01(\r2u\n\x08\x46\x65\x64Learn\x12/\n\x0bSendWeights\x12\x0f.SendWeightsReq\x1a\x0f.SendWeightsRes\x12\x38\n\x0eRequestWeights\x12\x12.RequestWeightsReq\x1a\x12.RequestWeightsResB\x08Z\x06pkg/pbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.fedlearn_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\006pkg/pb'
  _globals['_SENDWEIGHTSREQ']._serialized_start=24
  _globals['_SENDWEIGHTSREQ']._serialized_end=107
  _globals['_SENDWEIGHTSRES']._serialized_start=109
  _globals['_SENDWEIGHTSRES']._serialized_end=141
  _globals['_REQUESTWEIGHTSREQ']._serialized_start=143
  _globals['_REQUESTWEIGHTSREQ']._serialized_end=207
  _globals['_REQUESTWEIGHTSRES']._serialized_start=209
  _globals['_REQUESTWEIGHTSRES']._serialized_end=269
  _globals['_FEDLEARN']._serialized_start=271
  _globals['_FEDLEARN']._serialized_end=388
# @@protoc_insertion_point(module_scope)
