# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import fedlearn_pb2 as proto_dot_fedlearn__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/fedlearn_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FedLearnStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendWeights = channel.unary_unary(
                '/FedLearn/SendWeights',
                request_serializer=proto_dot_fedlearn__pb2.SendWeightsReq.SerializeToString,
                response_deserializer=proto_dot_fedlearn__pb2.SendWeightsRes.FromString,
                _registered_method=True)
        self.RequestWeights = channel.unary_unary(
                '/FedLearn/RequestWeights',
                request_serializer=proto_dot_fedlearn__pb2.RequestWeightsReq.SerializeToString,
                response_deserializer=proto_dot_fedlearn__pb2.RequestWeightsRes.FromString,
                _registered_method=True)


class FedLearnServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FedLearnServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.SendWeights,
                    request_deserializer=proto_dot_fedlearn__pb2.SendWeightsReq.FromString,
                    response_serializer=proto_dot_fedlearn__pb2.SendWeightsRes.SerializeToString,
            ),
            'RequestWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestWeights,
                    request_deserializer=proto_dot_fedlearn__pb2.RequestWeightsReq.FromString,
                    response_serializer=proto_dot_fedlearn__pb2.RequestWeightsRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'FedLearn', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('FedLearn', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FedLearn(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FedLearn/SendWeights',
            proto_dot_fedlearn__pb2.SendWeightsReq.SerializeToString,
            proto_dot_fedlearn__pb2.SendWeightsRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/FedLearn/RequestWeights',
            proto_dot_fedlearn__pb2.RequestWeightsReq.SerializeToString,
            proto_dot_fedlearn__pb2.RequestWeightsRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
