// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/fedlearn.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendWeightsReq struct {
	ClientId             uint32   `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientDataSize       uint32   `protobuf:"varint,2,opt,name=client_data_size,json=clientDataSize,proto3" json:"client_data_size,omitempty"`
	WeightsData          []byte   `protobuf:"bytes,3,opt,name=weights_data,json=weightsData,proto3" json:"weights_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendWeightsReq) Reset()         { *m = SendWeightsReq{} }
func (m *SendWeightsReq) String() string { return proto.CompactTextString(m) }
func (*SendWeightsReq) ProtoMessage()    {}
func (*SendWeightsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59ed6e634863f4be, []int{0}
}

func (m *SendWeightsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendWeightsReq.Unmarshal(m, b)
}
func (m *SendWeightsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendWeightsReq.Marshal(b, m, deterministic)
}
func (m *SendWeightsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendWeightsReq.Merge(m, src)
}
func (m *SendWeightsReq) XXX_Size() int {
	return xxx_messageInfo_SendWeightsReq.Size(m)
}
func (m *SendWeightsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendWeightsReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendWeightsReq proto.InternalMessageInfo

func (m *SendWeightsReq) GetClientId() uint32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *SendWeightsReq) GetClientDataSize() uint32 {
	if m != nil {
		return m.ClientDataSize
	}
	return 0
}

func (m *SendWeightsReq) GetWeightsData() []byte {
	if m != nil {
		return m.WeightsData
	}
	return nil
}

type SendWeightsRes struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendWeightsRes) Reset()         { *m = SendWeightsRes{} }
func (m *SendWeightsRes) String() string { return proto.CompactTextString(m) }
func (*SendWeightsRes) ProtoMessage()    {}
func (*SendWeightsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59ed6e634863f4be, []int{1}
}

func (m *SendWeightsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendWeightsRes.Unmarshal(m, b)
}
func (m *SendWeightsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendWeightsRes.Marshal(b, m, deterministic)
}
func (m *SendWeightsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendWeightsRes.Merge(m, src)
}
func (m *SendWeightsRes) XXX_Size() int {
	return xxx_messageInfo_SendWeightsRes.Size(m)
}
func (m *SendWeightsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SendWeightsRes.DiscardUnknown(m)
}

var xxx_messageInfo_SendWeightsRes proto.InternalMessageInfo

func (m *SendWeightsRes) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type RequestWeightsReq struct {
	ClientId             uint32   `protobuf:"varint,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientDataSize       uint32   `protobuf:"varint,2,opt,name=client_data_size,json=clientDataSize,proto3" json:"client_data_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestWeightsReq) Reset()         { *m = RequestWeightsReq{} }
func (m *RequestWeightsReq) String() string { return proto.CompactTextString(m) }
func (*RequestWeightsReq) ProtoMessage()    {}
func (*RequestWeightsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_59ed6e634863f4be, []int{2}
}

func (m *RequestWeightsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestWeightsReq.Unmarshal(m, b)
}
func (m *RequestWeightsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestWeightsReq.Marshal(b, m, deterministic)
}
func (m *RequestWeightsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestWeightsReq.Merge(m, src)
}
func (m *RequestWeightsReq) XXX_Size() int {
	return xxx_messageInfo_RequestWeightsReq.Size(m)
}
func (m *RequestWeightsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestWeightsReq.DiscardUnknown(m)
}

var xxx_messageInfo_RequestWeightsReq proto.InternalMessageInfo

func (m *RequestWeightsReq) GetClientId() uint32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func (m *RequestWeightsReq) GetClientDataSize() uint32 {
	if m != nil {
		return m.ClientDataSize
	}
	return 0
}

type RequestWeightsRes struct {
	WeightsData          []byte   `protobuf:"bytes,1,opt,name=weights_data,json=weightsData,proto3" json:"weights_data,omitempty"`
	ClientId             uint32   `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestWeightsRes) Reset()         { *m = RequestWeightsRes{} }
func (m *RequestWeightsRes) String() string { return proto.CompactTextString(m) }
func (*RequestWeightsRes) ProtoMessage()    {}
func (*RequestWeightsRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_59ed6e634863f4be, []int{3}
}

func (m *RequestWeightsRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestWeightsRes.Unmarshal(m, b)
}
func (m *RequestWeightsRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestWeightsRes.Marshal(b, m, deterministic)
}
func (m *RequestWeightsRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestWeightsRes.Merge(m, src)
}
func (m *RequestWeightsRes) XXX_Size() int {
	return xxx_messageInfo_RequestWeightsRes.Size(m)
}
func (m *RequestWeightsRes) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestWeightsRes.DiscardUnknown(m)
}

var xxx_messageInfo_RequestWeightsRes proto.InternalMessageInfo

func (m *RequestWeightsRes) GetWeightsData() []byte {
	if m != nil {
		return m.WeightsData
	}
	return nil
}

func (m *RequestWeightsRes) GetClientId() uint32 {
	if m != nil {
		return m.ClientId
	}
	return 0
}

func init() {
	proto.RegisterType((*SendWeightsReq)(nil), "SendWeightsReq")
	proto.RegisterType((*SendWeightsRes)(nil), "SendWeightsRes")
	proto.RegisterType((*RequestWeightsReq)(nil), "RequestWeightsReq")
	proto.RegisterType((*RequestWeightsRes)(nil), "RequestWeightsRes")
}

func init() {
	proto.RegisterFile("proto/fedlearn.proto", fileDescriptor_59ed6e634863f4be)
}

var fileDescriptor_59ed6e634863f4be = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0x85, 0x90, 0x4e, 0x6b, 0xd4, 0x41, 0x24, 0xd4, 0x4b, 0xcd, 0x29, 0xa7, 0x04,
	0xf4, 0xe2, 0x59, 0x44, 0x10, 0x3c, 0x6d, 0x0e, 0x42, 0x2f, 0x65, 0xeb, 0x8e, 0x75, 0xb1, 0xa4,
	0x69, 0x67, 0x82, 0x90, 0x5f, 0x2f, 0xdd, 0xe4, 0x60, 0xb2, 0x57, 0x8f, 0xf3, 0xed, 0x63, 0xde,
	0x9b, 0xb7, 0x70, 0x5d, 0x1f, 0xf7, 0xb2, 0x2f, 0x3e, 0xc9, 0xec, 0x48, 0x1f, 0xab, 0xdc, 0x8d,
	0x69, 0x0b, 0x71, 0x49, 0x95, 0x79, 0x27, 0xbb, 0xfd, 0x12, 0x56, 0x74, 0xc0, 0x5b, 0x98, 0x7e,
	0xec, 0x2c, 0x55, 0xb2, 0xb6, 0x26, 0x09, 0x96, 0x41, 0x76, 0xae, 0xa2, 0x0e, 0xbc, 0x1a, 0xcc,
	0xe0, 0xb2, 0x7f, 0x34, 0x5a, 0xf4, 0x9a, 0x6d, 0x4b, 0xc9, 0xc4, 0x69, 0xe2, 0x8e, 0x3f, 0x6b,
	0xd1, 0xa5, 0x6d, 0x09, 0xef, 0x60, 0xfe, 0xd3, 0x2d, 0x75, 0xd2, 0xe4, 0x6c, 0x19, 0x64, 0x73,
	0x35, 0xeb, 0xd9, 0x49, 0x96, 0x66, 0x23, 0x6f, 0xc6, 0x1b, 0x08, 0x59, 0xb4, 0x34, 0xec, 0x8c,
	0xa7, 0xaa, 0x9f, 0xd2, 0x15, 0x5c, 0x29, 0x3a, 0x34, 0xc4, 0xf2, 0xef, 0x41, 0xd3, 0xd2, 0xdf,
	0xcd, 0x5e, 0xfa, 0xc0, 0x4b, 0x3f, 0xb4, 0x9f, 0x0c, 0xed, 0xef, 0x1b, 0x88, 0x5e, 0xc8, 0xbc,
	0x9d, 0x8a, 0xc6, 0x02, 0x66, 0x7f, 0xce, 0xc4, 0x8b, 0x7c, 0x58, 0xf8, 0x62, 0x04, 0x18, 0x1f,
	0x21, 0x1e, 0x26, 0x42, 0xcc, 0xbd, 0xf3, 0x17, 0x3e, 0xe3, 0xa7, 0x68, 0x15, 0xd6, 0xdf, 0xdb,
	0xa2, 0xde, 0x6c, 0x42, 0xf7, 0xbd, 0x0f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf7, 0xcf, 0xa4,
	0x95, 0xf6, 0x01, 0x00, 0x00,
}
